### ISSUE TITLE
Module 'spikeextractors' has no attribute 'AxonaRecordingExtractor'

### ISSUE THREAD

**Issue by Willaem** [catalystneuro/nwb-conversion-tools#251]
## Description

In `datainterfaces/__init__.py`
During module loading, nwb-conversion-tools seems to fail to import AxonaRecordingExtractorInterface and AxonaPositionDataInterface. Since I don't use them (yet), disabling the importation and removing them from the `interface_list` in the same file was a temporary fix for that problem.

## Steps to Reproduce

The bug happened when trying to import NWBConverter from nwb_conversion_tools.

Here is the traceback : 

```py
Traceback (most recent call last):
  File "C:/Users/wlecl/PycharmProjects/nwb-ui-converter/src/nwbuiconverter/gui/flclabGui.py", line 12, in <module>
    from convCards import TifCard, AbfCard, LsmCard, CziCard
  File "C:\Users\wlecl\PycharmProjects\nwb-ui-converter\src\nwbuiconverter\gui\convCards.py", line 8, in <module>
    from nwb_conversion_tools import NWBConverter, TiffImagingInterface
  File "C:\Users\wlecl\PycharmProjects\nwb-ui-converter\virtualEnv\lib\site-packages\nwb_conversion_tools\__init__.py", line 3, in <module>
    from .datainterfaces import *
  File "C:\Users\wlecl\PycharmProjects\nwb-ui-converter\virtualEnv\lib\site-packages\nwb_conversion_tools\datainterfaces\__init__.py", line 26, in <module>
    from .ecephys.axona.axonadatainterface import AxonaRecordingExtractorInterface, AxonaPositionDataInterface
  File "C:\Users\wlecl\PycharmProjects\nwb-ui-converter\virtualEnv\lib\site-packages\nwb_conversion_tools\datainterfaces\ecephys\axona\axonadatainterface.py", line 70, in <module>
    class AxonaRecordingExtractorInterface(BaseRecordingExtractorInterface):
  File "C:\Users\wlecl\PycharmProjects\nwb-ui-converter\virtualEnv\lib\site-packages\nwb_conversion_tools\datainterfaces\ecephys\axona\axonadatainterface.py", line 73, in AxonaRecordingExtractorInterface
    RX = se.AxonaRecordingExtractor
AttributeError: module 'spikeextractors' has no attribute 'AxonaRecordingExtractor'
```

**Comment by bendichter** [comment]
@Willaem can you please include the code that reproduced this and the entire traceback?

**Comment by bendichter** [comment]
it looks like you might have an outdated `spikeextractors`. Can you run `pip install -U nwb-conversion-tools`

**Comment by Willaem** [comment]
> it looks like you might have an outdated `spikeextractors`. Can you run `pip install -U nwb-conversion-tools`

It seems like it was indeed the case. Thanks for the quick response!
