### ISSUE TITLE
Error when running source file using nwb_conversion_gui

### ISSUE THREAD

**Issue by Saksham20** [catalystneuro/nwb-conversion-tools#29]
There is an issue that I have hit when using the gui to run the SegExtractor conversion: 
I created a file: [here ](https://github.com/catalystneuro/nwb-conversion-tools/blob/SegExt-integration/nwb_conversion_tools/ophys/sima/simaconverter.py). It runs fine programmatically but gives an error when using the gui:
```
metafile = here + r'ophys\datasets\nct_ophys_metafile.yaml'
        sima_fileloc = here + r'ophys\datasets\dataset_hdf5.sima'
        nwbloc = here + r'ophys\datasets\test_nwb_sima.nwb'
        conversion_module = r'C:\nwb-conversion-tools\nwb_conversion_tools\ophys\sima\simaconverter.py'
        source_paths = dict(sima_path=dict(type='folder', path=sima_fileloc))

        kwargs_fields = {}

        nwb_conversion_gui(
            metafile=metafile,
            conversion_module=conversion_module,
            source_paths=source_paths,
            kwargs_fields=kwargs_fields
        )
```
Error: 
[Ophys.zip](https://github.com/catalystneuro/nwb-conversion-tools/files/4604477/Ophys.zip)

```
Traceback (most recent call last):
  File "C:\Users\Saksham\Google Drive (sxs1790@case.edu)\NWB\SegmentationExtractors\venv\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-1bffb4b3b1b5>", line 13, in <module>
    kwargs_fields=kwargs_fields)
  File "c:\users\saksham\google drive (sxs1790@case.edu)\nwb\nwb-conversion-tools\nwb_conversion_tools\gui\nwb_conversion_gui.py", line 696, in nwb_conversion_gui
    show_add_del=show_add_del
  File "c:\users\saksham\google drive (sxs1790@case.edu)\nwb\nwb-conversion-tools\nwb_conversion_tools\gui\nwb_conversion_gui.py", line 57, in __init__
    self.load_meta_file(filename=metafile)
  File "c:\users\saksham\google drive (sxs1790@case.edu)\nwb\nwb-conversion-tools\nwb_conversion_tools\gui\nwb_conversion_gui.py", line 378, in load_meta_file
    self.update_forms()
  File "c:\users\saksham\google drive (sxs1790@case.edu)\nwb\nwb-conversion-tools\nwb_conversion_tools\gui\nwb_conversion_gui.py", line 515, in update_forms
    group=self.name_to_gui_class[subgroup](parent=item),
KeyError: 'DFOverF'
```
Attached is the ophys folder which contains the dataset files and the metadata nct_ophys_metafile.yaml

**Comment by luiztauffer** [comment]
This errror happens when trying to find the right pynwb class to create the form for.
Those are defined in the yaml file, and the right way to name is `DfOverF`, with a lowercase f after D.
Can you try renaming the yaml file and see if it goes through?

**Comment by luiztauffer** [comment]
This was fixed by just using the proper name DfOverF, but led to other errors, which were due to some Ophys forms not being updated in the last refactor of forms.
579152b4a9f5effd8a68c4bb154c2949996c834e should fix it.

@Saksham20 can you please check it?
