### ISSUE TITLE
NeuroscopeSorting conversion fails on final io.write() step

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/nwb-conversion-tools#80]
This simple code extracted from the full conversion class

```
temp = this_converter.data_interface_objects['NeuroscopeSorting'].sorting_extractor
spikeextractors.NwbSortingExtractor.write_sorting(temp, save_path=nwbfile_path)
```

produces the following traceback.

Traceback (most recent call last):

```
  File "C:\Users\tobiruff\Downloads\buzsaki-lab-to-nwb\buzsaki_lab_to_nwb\tobi_code\convert_tobi.py", line 25, in <module>
    spikeextractors.NwbSortingExtractor.write_sorting(temp, save_path=nwbfile_path)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\spikeextractors\extractors\nwbextractors\nwbextractors.py", line 1204, in write_sorting
    io.write(nwbfile)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 323, in write
    call_docval_func(super().write, kwargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 405, in call_docval_func
    return func(*fargs, **fkwargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\backends\io.py", line 45, in write
    self.write_builder(f_builder, **kwargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 716, in write_builder
    self.write_group(self.__file, gbldr, **kwargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 908, in write_group
    self.set_attributes(group, attributes)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\utils.py", line 561, in func_call
    return func(args[0], **pargs)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\hdmf\backends\hdf5\h5tools.py", line 849, in set_attributes
    obj.attrs[key] = value

  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper

  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\h5py\_hl\attrs.py", line 103, in __setitem__
    self.create(name, data=value)

  File "C:\Users\tobiruff\AppData\Local\Continuum\anaconda2\envs\nwb_conversion_env\lib\site-packages\h5py\_hl\attrs.py", line 180, in create
    htype = h5t.py_create(original_dtype, logical=True)

  File "h5py\h5t.pyx", line 1629, in h5py.h5t.py_create

  File "h5py\h5t.pyx", line 1653, in h5py.h5t.py_create

  File "h5py\h5t.pyx", line 1719, in h5py.h5t.py_create

TypeError: No conversion path for dtype: dtype('<U11')
```

The unit_ids and unit_spike_trains seem to be initialized and retrieved fine by the NeuroscopeSortingExtractor.

**Comment by CodyCBakerPhD** [comment]
If you could, try running [this script](https://github.com/catalystneuro/to-nwb-template/blob/sorting_template/example_sorting/run_converter_sorting.py) on the `to-nwb-template` repository, `sorting_template` branch and see if the issue exists for  non-Neuroscope sorting extractors, too.

**Comment by wuffi** [comment]
It's a good idea to use the `example_dataset`.
Trying to run the following code

```
import spikeextractors

#nwbfile_path="D:\sample_data\sample_data.nwb"
nwbfile_path="/home/user/sample_data.nwb"

temp = spikeextractors.example_datasets.toy_example()[1]
spikeextractors.NwbSortingExtractor.write_sorting(temp, save_path=nwbfile_path)
```

works well on Linux.

(I'm still having issues with the Windows setup, that's why I will cross-validate everything in addition on Linux).

**Comment by bendichter** [comment]
Thanks for testing our code cross platform!
